### ISSUE TITLE
Rename repository to awesome-remark

### ISSUE THREAD

**Issue by RichardLitt** [remarkjs/awesome-remark#1]
I'm afraid it might be missed by some people searching for it, otherwise.

**Comment by wooorm** [comment]
I modelled this after https://github.com/Level/awesome, I’m fine using what you’re proposing though!

**Comment by RichardLitt** [comment]
Oh! It's not named after [sindresorhus/awesome](https://github.com/sindresorhus/awesome/)? So, it's not supposed to be an awesome list?

**Comment by wooorm** [comment]
Oh whoops, it’s also modelled after that hah. Just thought the duplication was redundant. I’m fine with remarkjs/awesome-remark tho!

**Comment by RichardLitt** [comment]
It doesn't look like it needs to be renamed according to the list guidelines, but I think it should match the convention. 

There are other guidelines to follow:

- [x] **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
- [ ] It's the result of hard work and the best I could possibly produce.
- [x] Non-generated Markdown file in a GitHub repo.
- [x] **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
- [x] The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
- [ ] Not a duplicate.
- [ ] Only has awesome items. Awesome lists are curations of the best, not everything.
- [ ] Includes a project logo/illustration whenever possible.
	- [ ] Either centered, fullwidth, or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
	- [ ] The image should link to the project website or any relevant website.
	- [ ] The image should be high-DPI. Set it to maximum half the width of the original image.
- [ ] Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
- [x] Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge).
	- [x] Should be placed on the right side of the readme heading.
		- [x] Can be placed centered if the list has a centered graphics header.
	- [ ] Should link back to this list.
- [ ] Has a Table of Contents section.
	- [ ] Should be named `Contents`, not `Table of Contents`.
	- [ ] Should be the first section in the list.
	- [ ] Should only have one level of [nested lists](https://commonmark.org/help/tutorial/10-nestedLists.html), preferably none.
- [ ] Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
	- [ ] That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
	- [ ] [WTFPL](http://www.wtfpl.net) and [Unlicense](http://unlicense.org) are not acceptable licenses.
	- [ ] If you use a license badge, it should be SVG, not PNG.
- [ ] Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
	- [ ] The file should be named `contributing.md`. Casing is up to you.
- [ ] Has consistent formatting and proper spelling/grammar.
	- [ ] The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
	- [ ] The description starts with an uppercase character and ends with a period.
	- [ ] Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
- [x] Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.

**Comment by ChristianMurphy** [comment]
Renamed.
Thanks for looking into the guidelines @RichardLitt! Moved these to #4 to raise the visibility.
