### ISSUE TITLE
Apply Awesome List Guidelines

### ISSUE THREAD

**Issue by ChristianMurphy** [remarkjs/awesome-remark#4]
There are other guidelines to follow:

- [x] **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
- [x] It's the result of hard work and the best I could possibly produce.
- [x] Non-generated Markdown file in a GitHub repo.
- [x] **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
- [x] The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
- [x] Not a duplicate.
- [x] Only has awesome items. Awesome lists are curations of the best, not everything.
- [x] Includes a project logo/illustration whenever possible.
	- [x] Either centered, fullwidth, or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
	- [x] The image should link to the project website or any relevant website.
	- [x] The image should be high-DPI. Set it to maximum half the width of the original image.
- [x] Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
- [x] Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge).
	- [x] Should be placed on the right side of the readme heading.
		- [x] Can be placed centered if the list has a centered graphics header.
	- [x] Should link back to this list.
- [x] Has a Table of Contents section.
	- [x] Should be named `Contents`, not `Table of Contents`.
	- [x] Should be the first section in the list.
	- [x] Should only have one level of [nested lists](https://commonmark.org/help/tutorial/10-nestedLists.html), preferably none.
- [x] Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
	- [x] That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
	- [x] [WTFPL](http://www.wtfpl.net) and [Unlicense](http://unlicense.org) are not acceptable licenses.
	- [x] If you use a license badge, it should be SVG, not PNG.
- [x] Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
	- [x] The file should be named `contributing.md`. Casing is up to you.
- [x] Has consistent formatting and proper spelling/grammar.
	- [x] The link and description are separated by a dash. <br>Example: `- [AVA](…) - JavaScript test runner.`
	- [x] The description starts with an uppercase character and ends with a period.
	- [x] Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
- [x] Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.

_Originally posted by @RichardLitt in https://github.com/remarkjs/awesome/issues/1#issuecomment-440351072_

**Comment by RichardLitt** [comment]
Added some badges. A lot of the tasks needed here are something a community member who is just landing on this repository and wants to help out can do. If you want to help out, feel free to dive in, reader. :)
