### ISSUE TITLE
add termd

### ISSUE THREAD

**Issue by ephraimduncan** [remarkjs/awesome-remark#8]
[termd](https://github.com/dephraiim/termd) is a cli for previewing and rendering markdown files in the terminal based on remark.

**Comment by wooorm** [comment]
Hi there! Nice project & thanks for building on remark! There are also similar projects like termd, such as [`vweevers/markdown-to-ansi`](https://github.com/vweevers/markdown-to-ansi) which I saw recently, that you might want to work with / learn from.

I do think this project is a bit too new, not used a lot yet, and doesn’t have a lot of stars yet either. So, similar to [awesome-node](https://github.com/sindresorhus/awesome-nodejs/blob/master/contributing.md), I think “30 days old and the repo should have at least 40 stars.” is a good limit for which things fit well on this list here.
